### ISSUE TITLE
In My project , the action isnt detecting my testcases 

### ISSUE THREAD

**Issue by DanyalKhaliqEMPG** [programmingwithalex/pytester-cover#1]
Hey Alex , first up thanks for the great action tool for test coverage . I tried your sample project it works fine .
However in my project its not detecting my testcase no matter when I put them in (be it in root level 'test' folder or a 'test' folder inside the project itself . 

directory struc is something like this 

- root 
  - apps
     - project1
     - project2
     - ...
  - test
     - project1test.py
     - project2test.py 
     - etc 
     
I have tried moving the test folder inside the project too but its not detecting test cases either.  
sample code for test file is like below . test cases work fine locally and in github actions but issues is with coverage 
There are couple of test files (oldones) which uses '**unittest**' , coverage interestingly though detects it and shows the covereged for those files 

`
import pytest

import sys

sys.path.append("../kitt-carprice-lib-trends-batch-api/")

from scripts import business_rules

def test__check_ranges():
    mock_business_rules = business_rules.BusinessRules(
        event_payload=dict(new_car_price=2000)
    )
    assert mock_business_rules._check_ranges(120, 100, 1) == False
    assert mock_business_rules._check_ranges(120, 119, 1) == True

def test__format_return():
    mock_business_rules = business_rules.BusinessRules(
        event_payload=dict(new_car_price=2000)
    )
    assert mock_business_rules._format_return() == dict(
        business_confidence_traffic_light=None,
        managed_fair_selling_price=None,
        message=""
    )

    mock_business_rules.managed_fair_selling_price = 10000
    mock_business_rules.business_confidence_traffic_light = "red"

    assert mock_business_rules._format_return() == dict(
        business_confidence_traffic_light="red",
        managed_fair_selling_price=10000,
        message="",
    )
`

**Comment by programmingwithalex** [comment]
Could you link me your repo so I can fork it and take a look?

**Comment by DanyalKhaliqEMPG** [comment]
Sure this is the link 
https://github.com/DanyalKhaliqEMPG/test_repo_pytester

I want to ask why the action isn't looking into other folders which has the 'test' folder in it . like below its only calculating for the Books folder which it encounter first (alphabetically ) and leaves to traverse the trans folder which also has a 'test' folder with tests ? 



Name | Stmts | Miss | Cover
-- | -- | -- | --
apps/book/scripts/init.py | 0 | 0 | 100%
apps/book/scripts/main.py | 11 | 6 | 45%
apps/trans/scripts/init.py | 0 | 0 | 100%
apps/trans/scripts/main3.py | 9 | 9 | 0%
TOTAL | 20 | 15 | 25%

**Comment by programmingwithalex** [comment]
@DanyalKhaliqEMPG I looked at your repository. The issue is the `test` or `tests` directory should be at the top-level of the repo. It's not standard practice to have separate `test` directories in subfolders. You should instead have the `test` directory in the top-level and replicate the subdirectory structure. For example:

```
.
└───test
│   └───apps
│       └───book
│       └───trans
```
