### ISSUE TITLE
Docs on step output is inconsistent

### ISSUE THREAD

**Issue by clint-richardson** [programmingwithalex/pytester-cover#2]
[The documentation ](https://github.com/marketplace/actions/pytester-cov#outputs)suggests that the booleans for single/total threshold failures are 'true' if all tests have **more** coverage than the threshold, and false if any single one is below threshold.

```
cov-threshold-single-fail
boolean
false if any single file coverage less than cov-threshold-single, else true
cov-threshold-total-fail
boolean
false if total coverage less than cov-threshold-total, else true
```

This is inconsistent with the example usage which exits on them being false:

```
 - name: Coverage total fail - exit
      if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
```

its also inconsistent with the documentation of these outputs in the underlying actions yaml file: https://github.com/programmingwithalex/pytester-cov/blob/main/action.yml#L37-L40

**Comment by programmingwithalex** [comment]
@clint-richardson Thanks for pointing this out. It has been fixed.
